services:
  backend:
    image: rajvardhan1110/campus-tales-backend:latest
    container_name: campus-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always

  frontend:
    image: rajvardhan1110/campus-tales-frontend:latest
    container_name: campus-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
